ovm_vm { 'default/repo01/server_pool_1/ovs01.example.com/myvm1':
  ensure                  => 'present',
  boot_order              => ['DISK', 'CDROM'],
  cpu_count               => 2,
  cpu_count_limit         => 2,
  cpu_priority            => 50,
  cpu_utilization_cap     => 100,
  description             => 'Test 1',
  keymap_name             => 'en-us',
  memory                  => 192,
  memory_limit            => 192,
  os_type                 => 'Oracle Linux 7',
  restart_action_on_crash => 'RESTART',
  virtual_disks           => ['0:repo01/CentOS-7-livecd-x86_64.iso', '1:repo01/vm01_disk', '2:physical/OVM_SYS_REPO_PART_1ATA_VBOX_HARDDISK_VB0a63b278-8f6825a5', '3:physical/OPNFILER (1)'],
  vm_domain_type          => 'XEN_HVM',
  vm_mouse_type           => 'OS_DEFAULT',
  vm_run_state            => 'STOPPED',
  vm_start_policy         => 'BEST_SERVER',
}

